- id: '1742259737852'
  alias: Office Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_1
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_ceiling_natural_light
- id: '1742259802006'
  alias: Office Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_2
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_ceiling_nightlight
- id: '1742259852048'
  alias: 'Office Switch Button 3 '
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_3
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_ceiling_relax
- id: '1742265800631'
  alias: Bedroom Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_1
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_bedside_natural_light
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_ceiling_natural_light
- id: '1742265845066'
  alias: Bedroom Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_2
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_bedside_read
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_ceiling_mood
- id: '1742265919265'
  alias: Bedroom Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_3
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_bedside_play
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_ceiling_play
- id: '1742268121309'
  alias: Loft Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_1
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.loft_ceiling_natural_light
- id: '1742273165518'
  alias: Loft Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_2
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.loft_ceiling_resplendent
- id: '1742273188065'
  alias: Loft Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_3
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.loft_ceiling_play
- id: '1742337005391'
  alias: Office Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.office_ceiling
      switch: switch.office_switch
- id: '1742337248521'
  alias: Loft Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.loft_ceiling
      switch: switch.loft_switch
- id: '1742337280749'
  alias: Bedroom Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.bedroom
      switch: switch.bedroom_switch
- id: '1742337322652'
  alias: Dining Room Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.dining_room
      switch: switch.dining_room_switch
- id: '1742347526685'
  alias: Bedroom Occupancy
  description: ''
  use_blueprint:
    path: light_occupancy.yaml
    input:
      light: light.bedroom
      sensor: binary_sensor.bedroom_occupancy
      awake: binary_sensor.household_asleep
      asleep: binary_sensor.household_asleep
- id: '1742347574417'
  alias: Loft Occupancy
  description: ''
  use_blueprint:
    path: light_occupancy.yaml
    input:
      light: light.loft_ceiling
      sensor: binary_sensor.loft_occupancy
- id: '1742347602151'
  alias: Office Occupancy
  description: ''
  use_blueprint:
    path: light_occupancy.yaml
    input:
      light: light.office_ceiling
      sensor: binary_sensor.office_occupancy
- id: '1744102789672'
  alias: Dining Room Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_1
      actions:
      - action: light.toggle
        metadata: {}
        data:
          brightness_pct: 100
        target:
          entity_id:
          - light.dining_room_chandelier
          - light.dining_room_spots
- id: '1745017281980'
  alias: Bedroom Pico Raise
  description: ''
  triggers:
  - device_id: b0881bdabe428061b6e34aa09b9386d6
    domain: lutron_caseta
    type: press
    subtype: raise
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.bedroom_nighttime
  mode: single
- id: '1745017343700'
  alias: Bedroom Pico Lower
  description: ''
  triggers:
  - device_id: b0881bdabe428061b6e34aa09b9386d6
    domain: lutron_caseta
    type: press
    subtype: lower
    trigger: device
  conditions: []
  actions:
  - wait_for_trigger:
    - device_id: b0881bdabe428061b6e34aa09b9386d6
      domain: lutron_caseta
      type: release
      subtype: lower
      trigger: device
    timeout:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - if:
    - condition: template
      value_template: '{{ wait.completed }}'
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.bedroom_daytime
    else:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.bedroom_window_open
  mode: single
- id: '1745036152820'
  alias: Office Pico Raise
  description: ''
  triggers:
  - device_id: beb7140be21d2a179f64ec52b946edca
    domain: lutron_caseta
    type: press
    subtype: raise
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_nighttime
  mode: single
- id: '1745036342899'
  alias: Office Pico Lower
  description: ''
  triggers:
  - device_id: beb7140be21d2a179f64ec52b946edca
    domain: lutron_caseta
    type: press
    subtype: lower
    trigger: device
  conditions: []
  actions:
  - wait_for_trigger:
    - device_id: beb7140be21d2a179f64ec52b946edca
      domain: lutron_caseta
      type: release
      subtype: lower
      trigger: device
    timeout:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - if:
    - condition: template
      value_template: '{{ wait.completed }}'
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.office_daytime
    else:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.hunter_douglas_office_window_open
  mode: single
- id: '1745249879161'
  alias: Dining Room Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_3
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - scene.dining_room_beam_lights_play
          - scene.dining_room_wall_play
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - scene.dining_room_windows_closed
          - scene.kitchen_windows_closed
- id: '1747753451904'
  alias: Bedroom Play
  description: ''
  triggers:
  - trigger: state
    entity_id: input_boolean.bedroom_play
    to:
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.bedroom_play
        state: 'on'
      sequence:
      - action: automation.turn_off
        target:
          entity_id:
          - automation.bedroom_occupancy
          - automation.bedroom_windows
        data:
          stop_actions: true
      - if:
        - condition: state
          entity_id: binary_sensor.bedroom_window
          state: 'off'
        then:
        - action: scene.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: scene.bedroom_nighttime
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.bedroom_ceiling
          - light.bedroom_bedside
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - action: scene.create
        metadata: {}
        data:
          scene_id: bedroom_play
          snapshot_entities:
          - light.bedroom_bedside
          - light.bedroom_ceiling
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - scene.bedroom_bedside_play
          - scene.bedroom_ceiling_play
    - conditions:
      - condition: state
        entity_id: input_boolean.bedroom_play
        state: 'off'
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_play
      - action: scene.delete
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_play
      - action: automation.trigger
        target:
          entity_id:
          - automation.bedroom_occupancy
          - automation.bedroom_windows
        data:
          skip_condition: true
      - action: automation.turn_on
        target:
          entity_id:
          - automation.bedroom_occupancy
          - automation.bedroom_windows
        data: {}
  mode: queued
- id: '1747753518535'
  alias: Dining Room Play
  description: ''
  triggers:
  - trigger: state
    entity_id: input_boolean.dining_room_play
    to:
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.dining_room_play
        state: 'on'
      sequence:
      - action: automation.turn_off
        target:
          entity_id:
          - automation.dining_room_motion_at_night
          - automation.dining_room_windows
          - automation.dining_room_mood_lights
          - automation.kitchen_windows
        data:
          stop_actions: true
      - if:
        - condition: state
          entity_id: binary_sensor.dining_room_top_windows
          state: 'off'
        - condition: state
          entity_id: binary_sensor.dining_room_bottom_windows
          state: 'off'
        then:
        - action: scene.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: scene.dining_room_windows_closed
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.kitchen_windows_closed
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.dining_room_wall
          - light.dining_room_beam
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - action: scene.create
        metadata: {}
        data:
          scene_id: dining_room_play
          snapshot_entities:
          - light.dining_room_wall
          - light.dining_room_beam
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - scene.dining_room_wall_play
          - scene.dining_room_beam_lights_play
    - conditions:
      - condition: state
        entity_id: input_boolean.dining_room_play
        state: 'off'
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.dining_room_play
      - action: scene.delete
        metadata: {}
        data: {}
        target:
          entity_id: scene.dining_room_play
      - action: automation.trigger
        target:
          entity_id:
          - automation.dining_room_motion_at_night
          - automation.dining_room_windows
          - automation.dining_room_mood_lights
          - automation.kitchen_windows
        data:
          skip_condition: true
      - action: automation.turn_on
        target:
          entity_id:
          - automation.dining_room_motion_at_night
          - automation.dining_room_windows
          - automation.dining_room_mood_lights
          - automation.kitchen_windows
        data: {}
  mode: queued
- id: '1747754063388'
  alias: On Vacation
  description: ''
  use_blueprint:
    path: disable_automations.yaml
    input:
      input: input_boolean.on_vacation
      automations:
      - automation.bedroom_occupancy
      - automation.dining_room_mood_lights
      - automation.dining_room_motion_at_night
      - automation.loft_occupancy
      - automation.office_occupancy
- id: '1749581120674'
  alias: Gaming Power Limit
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.gaming_power_limit
    to:
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: binary_sensor.gaming_power_limit
      state: 'on'
    then:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.vecna_power_limit_enable
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.office_desk_right_switch_1
    else:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.vecna_power_limit_disable
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.office_desk_right_switch_1
  mode: single
