- id: '1742259737852'
  alias: Office Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_1
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_ceiling_natural_light
- id: '1742259802006'
  alias: Office Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_2
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_ceiling_nightlight
- id: '1742259852048'
  alias: 'Office Switch Button 3 '
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_3
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_ceiling_relax
- id: '1742265800631'
  alias: Bedroom Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_1
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_bedside_natural_light
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_ceiling_natural_light
- id: '1742265845066'
  alias: Bedroom Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_2
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_bedside_read
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_ceiling_mood
- id: '1742265919265'
  alias: Bedroom Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_3
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_bedside_play
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_ceiling_play
- id: '1742268121309'
  alias: Loft Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_1
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.loft_ceiling_natural_light
- id: '1742273165518'
  alias: Loft Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_2
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.loft_ceiling_resplendent
- id: '1742273188065'
  alias: Loft Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_3
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.loft_ceiling_play
- id: '1742337005391'
  alias: Office Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.office_ceiling
      switch: switch.office_switch
- id: '1742337248521'
  alias: Loft Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.loft
      switch: switch.loft_switch
- id: '1742337280749'
  alias: Bedroom Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.bedroom
      switch: switch.bedroom_switch
- id: '1742337322652'
  alias: Dining Room Lights
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.dining_room
      switch: switch.dining_room_switch
- id: '1742347526685'
  alias: Bedroom Occupancy
  description: ''
  use_blueprint:
    path: light_occupancy.yaml
    input:
      light: light.bedroom
      sensor: binary_sensor.bedroom_occupancy
- id: '1742347574417'
  alias: Loft Occupancy
  description: ''
  use_blueprint:
    path: light_occupancy.yaml
    input:
      light: light.loft
      sensor: binary_sensor.loft_occupancy
- id: '1742347602151'
  alias: Office Occupancy
  description: ''
  use_blueprint:
    path: light_occupancy.yaml
    input:
      light: light.office_ceiling
      sensor: binary_sensor.office_occupancy
- id: '1744102789672'
  alias: Dining Room Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_1
      actions:
      - action: light.toggle
        metadata: {}
        data:
          brightness_pct: 100
        target:
          entity_id:
          - light.dining_room_chandelier
          - light.dining_room_spots
- id: '1745017281980'
  alias: Bedroom Pico Raise
  description: ''
  triggers:
  - device_id: b0881bdabe428061b6e34aa09b9386d6
    domain: lutron_caseta
    type: press
    subtype: raise
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.bedroom_nighttime
  mode: single
- id: '1745017343700'
  alias: Bedroom Pico Lower
  description: ''
  triggers:
  - device_id: b0881bdabe428061b6e34aa09b9386d6
    domain: lutron_caseta
    type: press
    subtype: lower
    trigger: device
  conditions: []
  actions:
  - wait_for_trigger:
    - device_id: b0881bdabe428061b6e34aa09b9386d6
      domain: lutron_caseta
      type: release
      subtype: lower
      trigger: device
    timeout:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - if:
    - condition: template
      value_template: '{{ wait.completed }}'
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.bedroom_daytime
    else:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.bedroom_window_open
  mode: single
- id: '1745036152820'
  alias: Office Pico Raise
  description: ''
  triggers:
  - device_id: beb7140be21d2a179f64ec52b946edca
    domain: lutron_caseta
    type: press
    subtype: raise
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_nighttime
  mode: single
- id: '1745036342899'
  alias: Office Pico Lower
  description: ''
  triggers:
  - device_id: beb7140be21d2a179f64ec52b946edca
    domain: lutron_caseta
    type: press
    subtype: lower
    trigger: device
  conditions: []
  actions:
  - wait_for_trigger:
    - device_id: beb7140be21d2a179f64ec52b946edca
      domain: lutron_caseta
      type: release
      subtype: lower
      trigger: device
    timeout:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - if:
    - condition: template
      value_template: '{{ wait.completed }}'
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.office_daytime
    else:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.hunter_douglas_office_window_open
  mode: single
- id: '1745249879161'
  alias: Dining Room Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_3
      actions:
      - action: input_boolean.toggle
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.dining_room_play
- id: '1747754063388'
  alias: On Vacation
  description: ''
  use_blueprint:
    path: disable_automations.yaml
    input:
      input: input_boolean.on_vacation
      automations:
      - automation.bedroom_occupancy
      - automation.dining_room_mood_lights
      - automation.dining_room_motion_at_night
      - automation.loft_occupancy
      - automation.office_occupancy
- id: '1749581120674'
  alias: Gaming Power Limit
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.gaming_power_limit
    to:
  - trigger: state
    entity_id:
    - sensor.vecna_lastsystemstatechange
    to:
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: binary_sensor.gaming_power_limit
      state: 'on'
    then:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.vecna_power_limit_enable
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.office_desk_right_switch_1
    else:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.vecna_power_limit_disable
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.office_desk_right_switch_1
  mode: queued
  max: 10
- id: '1750177081187'
  alias: Dining Room Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_2
      actions:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.dnd
- id: '1752608748598'
  alias: Office Pico Lower
  description: ''
  triggers:
  - device_id: beb7140be21d2a179f64ec52b946edca
    domain: lutron_caseta
    type: press
    subtype: lower
    trigger: device
  conditions: []
  actions:
  - wait_for_trigger:
    - device_id: beb7140be21d2a179f64ec52b946edca
      domain: lutron_caseta
      type: release
      subtype: lower
      trigger: device
    timeout:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - if:
    - condition: template
      value_template: '{{ wait.completed }}'
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.office_daytime
    else:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.office_window_open
  mode: single
- id: '1752608870374'
  alias: Office Pico Raise
  description: ''
  triggers:
  - device_id: beb7140be21d2a179f64ec52b946edca
    domain: lutron_caseta
    type: press
    subtype: raise
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_nighttime
  mode: single
- id: '1752632839285'
  alias: Bedroom Pico On
  description: ''
  triggers:
  - device_id: b0881bdabe428061b6e34aa09b9386d6
    domain: lutron_caseta
    type: press
    subtype: 'on'
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.bedroom_blackout
  mode: single
- id: '1752632870011'
  alias: Bedroom Pico Off
  description: ''
  triggers:
  - device_id: b0881bdabe428061b6e34aa09b9386d6
    domain: lutron_caseta
    type: press
    subtype: 'off'
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.bedroom_blackout_open
  mode: single
