blueprint:
  name: Disable Automations
  description: >
    Disable automations based on the state of an input boolean.
  author: Scott James Remnant <scott@netsplit.com>
  domain: automation
  input:
    input:
      name: Input
      description: Automations are disabled while this input is on.
      selector:
        entity:
          filter:
            - domain: input_boolean
    automations:
      name: Automations
      description: Automations disabled when the input is on.
      selector:
        entity:
          filter:
            - domain: automation
          multiple: true

mode: queued

triggers:
  - trigger: state
    entity_id: !input input
    to: null

actions:
  - choose:
    - conditions:
        - condition: state
          entity_id: !input input
          state: "on"
      sequence:
        - action: automation.turn_off
          target:
            entity_id: !input automations
    - conditions:
        - condition: state
          entity_id: !input input
          state: "off"
      sequence:
        - action: automation.trigger
          target:
            entity_id: !input automations
        - action: automation.turn_on
          target:
            entity_id: !input automations
