alias: Bedroom Windows
id: bedroom_windows
description: >
  Open and close the bedroom window blinds based on the time of day.

mode: queued

triggers:
  # Update blinds at sunset and sunrise.
  - trigger: state
    entity_id: sun.sun
    to: null
  # Update blinds when we wake up or go to sleep.
  - trigger: state
    entity_id: binary_sensor.household_asleep
    to: null
  # Update blinds when there is motion in the bedroom. We use the Ecobee for
  # this because the Nest points directly down at the bed.
  - trigger: state
    entity_id: binary_sensor.bedroom_ecobee_motion
    to: "on"
  # Update blinds when the windows are closed.
  - trigger: state
    entity_id: binary_sensor.bedroom_window
    to: "off"
  # Update blinds when Shadie comes home.
  - trigger: zone
    entity_id:
      - person.shadie
    zone: zone.home
    event: enter
  # Update blinds when we're playing.
  - trigger: state
    entity_id: input_boolean.bedroom_play
    from: null

actions:
  - choose:
    # Open blinds during the day.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        # Unless someone is sleeping.
        - condition: state
          entity_id: binary_sensor.household_asleep
          state: "off"
        # Unless we're playing.
        - condition: state
          entity_id: input_boolean.bedroom_play
          state: "off"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.bedroom_daytime
        - action: scene.turn_on
          target:
            entity_id: scene.bedroom_blackout_open

    # Close blinds while we're playing.
    - conditions:
        - condition: state
          entity_id: input_boolean.bedroom_play
          state: "on"
        # Only when the windows are closed.
        - condition: state
          entity_id: binary_sensor.bedroom_window
          state: "off"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.bedroom_nighttime

    # Close blinds at night.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        # Only when the windows are closed.
        - condition: state
          entity_id: binary_sensor.bedroom_window
          state: "off"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.bedroom_nighttime
        # Close blackout when Shadie is home.
        - if:
            - condition: state
              entity_id: person.shadie
              state: "home"
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.bedroom_blackout
