alias: Bedroom Windows
id: bedroom_windows
description: >
  Opens the bedroom window blinds in the morning once we're awake, and closes
  them at night provided the windows are closed.

mode: single

triggers:
  # Sunrise can trigger the windows opening if nobody is home.
  - trigger: state
    entity_id: sun.sun
    to: "above_horizon"
  # Everyone waking up can open the windows.
  - trigger: state
    entity_id: binary_sensor.household_asleep
    to: "off"
  # Motion in the bedroom should open the windows. We use the Ecobee for this
  # because the Nest points directly down at the bed.
  - trigger: state
    entity_id: binary_sensor.bedroom_ecobee_motion
    to: "on"
  # If nothing else has opened the windows, try opening them at 10am.
  - trigger: time
    at: "10:00:00"
  # Sunset triggers the window closing.
  - trigger: state
    entity_id: sun.sun
    to: "below_horizon"
  # We're careful not to close the blinds over open windows, so trigger on the
  # windows being closed.
  - trigger: state
    entity_id: binary_sensor.bedroom_window
    to: "off"

actions:
  - choose:
    # To open the window blinds, the sun has to be above the horizon, and nobody
    # should be asleep.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        - condition: state
          entity_id: binary_sensor.household_asleep
          state: "off"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.bedroom_daytime
        - action: scene.turn_on
          target:
            entity_id: scene.bedroom_blackout_open

    # To close the window blinds, the sun should be below the horizon, and the
    # windows should be closed.
    - conditions:
        - condition: state
          entity_id: binary_sensor.bedroom_window
          state: "off"
        - condition: state
          entity_id: sun.sun
          state: below_horizon
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.bedroom_nighttime
