alias: Dining Room Motion at Night
id: dining_room_motion_at_night
description: >
  Turns on the kitchen counter lights at night for midnight snacks.

mode: restart

triggers:
  # Trigger using the Eve Motion, as it's the most reliable.
  - trigger: state
    entity_id: binary_sensor.dining_room_motion_occupancy
    to: "on"

conditions:
  # Only at night.
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  # And only when the kitchen counter light is off, or at low brightness.
  # That way the script keeps the light on low as long as there is motion,
  # without turning it off unexpectedly.
  - or:
    - condition: state
      entity_id: light.kitchen_counter
      state: "off"
    - "{{ (state_attr('light.kitchen_counter', 'brightness') | int) <= 64 }}"

actions:
  # Turn on the kitchen counter at 25%. but leave it alone if already on.
  # Assume that takes a few seconds.
  - if:
      - condition: state
        entity_id: light.kitchen_counter
        state: "off"
    then:
      - action: light.turn_on
        data:
          brightness_pct: 25
        target:
          entity_id: light.kitchen_counter
      - delay:
          seconds: 5

  # Keep the light on for 15 minutes.
  # But if the kitchen counter state changes, assume we should leave it alone
  # and not turn it off in the middle of someone's burrito.
  - wait_for_trigger:
      - trigger: state
        entity_id: light.kitchen_counter
    timeout:
      minutes: 15
  - if:
      - "{{ not wait.completed }}"
    then:
      - action: light.turn_off
        target:
          entity_id: light.kitchen_counter
