alias: Dining Room Mood Lights
id: dining_room_mood_lights
description: >
  When anybody is (or comes) home in the evening, make sure that the Hue
  light bars and beams are making the brick work turn pretty colors.

mode: single

triggers:
  # Generally turn the lights on at sunset.
  - trigger: state
    entity_id: sun.sun
    to: "below_horizon"
  # Or when somebody comes home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to: "on"

actions:
  - choose:
    # Lights are turned on in the evening if somebody is home, and awake.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        - condition: state
          entity_id: binary_sensor.household_asleep
          state: "off"
        - condition: state
          entity_id: binary_sensor.anyone_home
          state: "on"
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Lights are turned off at midnight, we don't need to check the condition.
    default:
      - action: light.turn_off
        target:
          entity_id:
            - light.dining_room
            - light.dining_room_lego
