alias: Dining Room Lights
id: dining_room_lights
description: >
  When anybody is (or comes) home in the evening, make sure that the Hue
  light bars and beams are making the brick work turn pretty colors.

mode: queued

triggers:
  # Generally turn the lights on at sunset.
  - trigger: state
    entity_id: sun.sun
    to: "below_horizon"
  # Or when somebody comes home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to: "on"
  # Playing in the dining room keeps the lights on.
  - trigger: state
    entity_id: input_boolean.dining_room_play
    to: null

actions:
  - choose:
    # Lights are turned on in the evening if somebody is home, and awake.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        - condition: state
          entity_id: binary_sensor.household_asleep
          state: "off"
        - condition: state
          entity_id: binary_sensor.anyone_home
          state: "on"
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Otherwise lights are turned off unless we're playing.
    - conditions:
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: 'off'
      sequence:
        - action: light.turn_off
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego
