alias: Dining Room Lights
id: dining_room_lights
description: >
  Turn the dining room lights on while the home is occupied, making the brick
  work turn pretty colors.

mode: queued

triggers:
  # Update lights at sunset and sunrise.
  - trigger: state
    entity_id: sun.sun
    to: null
  # Update lights when we wake up or go to sleep.
  - trigger: state
    entity_id: binary_sensor.household_asleep
    to: null
  # Update lights when the first person comes home, or the last person leaves
  # home.
  - trigger: state
    entity_id: binary_sensor.anyone_home
    to: null

actions:
  - choose:
    # Turn lights on at night.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        # Unless someone is sleeping.
        - condition: state
          entity_id: binary_sensor.household_asleep
          state: "off"
        # Only when someone is home.
        - condition: state
          entity_id: binary_sensor.anyone_home
          state: "on"
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego

    # Otherwise turn lights off.
    - conditions:
        # Unless we're playing.
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: "off"
      sequence:
        - action: light.turn_off
          target:
            entity_id:
              - light.dining_room
              - light.dining_room_lego
