alias: Home Not Occupied
id: home_not_occupied
description: >
  Turns off lights when the home is no longer occupied.

mode: single

triggers:
  - trigger: state
    entity_id: binary_sensor.anyone_home
    from: "on"

actions:
  - action: light.turn_off
    target:
      area_id:
        # dining_room, bedroom, loft, and office have their own automations.
        - kitchen
        - downstairs_bathroom
        - bathroom
        - stairs
        - roof
