alias: Kitchen Windows
id: kitchen_windows
description: >
  Open and close the kitchen window blinds based on the time of day,
  sun position, and weather.

mode: queued

triggers:
  # Update blinds at sunset and sunrise.
  - trigger: state
    entity_id: sun.sun
    from: null
  # Trigger when sun shines through the kitchen windows by reaching
  # 115° azimuth.
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: 115
  # Trigger when sun is no longer shining through the windows by reaching
  # 235° azimith.
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: 235
  # Update blinds based on the weather, and forecast temperature.
  - trigger: state
    entity_id: weather.home
    to: null
  - trigger: numeric_state
    entity_id: weather.home
    attribute: temperature
    above: 69
  # Update blinds when the TV turns on or off.
  - trigger: state
    entity_id: media_player.lg_webos_tv
    from: null
  # Update blinds when we're playing.
  - trigger: state
    entity_id: input_boolean.dining_room_play
    from: null
  - trigger: state
    entity_id: input_boolean.loft_play
    from: null

variables:
  cloudy_day: >
    {{ states('weather.home') not in
       ['clear-night', 'partlycloudy', 'sunny', 'windy' ]
    }}

actions:
  - choose:
    # Close the blinds during the day when the sun is shining through the
    # windows, it's not cloudy, and it's forecast to be warm.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: azimuth
          above: 115
          below: 235
        - condition: numeric_state
          entity_id: weather.home
          attribute: temperature
          above: 69
        - "{{ not cloudy_day }}"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.kitchen_windows_closed

    # Close blinds while we're playing in the dining room.
    - conditions:
        - condition: state
          entity_id: input_boolean.dining_room_play
          state: "on"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.kitchen_windows_closed

    # Close the loft part of the blinds during the day when the TV is on.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        - condition: state
          entity_id: media_player.lg_webos_tv
          state: "on"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.kitchen_nighttime

    # Close the loft part of the blinds while we're playing in the loft.
    - conditions:
        - condition: state
          entity_id: input_boolean.loft_play
          state: "on"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.kitchen_nighttime

    # Open blinds during the day.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.kitchen_daytime

    # Close the loft part of the blinds at night.
    - conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
      sequence:
        - action: scene.turn_on
          target:
            entity_id: scene.kitchen_nighttime
